apiVersion: v1
kind: Service
metadata:
  name: udp-worker
spec:
  ports:
  - name: udp-inport
    port: 8080
    targetPort: 8080
    protocol: UDP
  selector:
    app: udp-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-worker
  template:
    metadata:
      labels:
        app: udp-worker
    spec:
      containers:
      - name: udp-worker
        image: andrewferguson/udptest:latest
        ports:
        - containerPort: 8080
          protocol: UDP
          name: udp-inport
        command: ["./server", "$(THIS_POD_IP)", "8080"]
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 5m
          requests:
            cpu: 2m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udp-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udp-worker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80